### ISSUE TITLE
Deprecation Explanation?

### ISSUE THREAD

**Issue by rayliverified** [inloop/svg2android#102]
This tool has been immensely helpful in Android development and I use it every day! 
Is there a reason why this tool is being deprecated? The tool in Android Studio is not as convenient.

**Comment by Neogene** [comment]
The native import tool of Android Studio doesn't support multiple files, so this tool is still useful.

**Comment by rayliverified** [comment]
^Yes, I'm glad this tool still works. The native tool is very cumbersome to use.

**Comment by davekover** [comment]
I exclusively use this for SVG conversion as the Android Studio tooling is not as straight forward. You can't get any simpler than the drop and go nature of this tool specifically.

**Comment by yuraj11** [comment]
Thanks for your feedback.
I appreciate your usage of my tool but the main reason is that this tool is now obsolete because AS vector asset studio has improved in last days and after looking to the conversion code I can tell that my tool is now behind the official solution. I would rather contribute to AOSP to improve the conversion process (I am lookin on It right now). I have tried converting some random SVGs and the offical one works better for me and there is no reason to upgrade this tool because either It is more integrated in AS and It is better than before. (Also my tool would need entire rewrite because the code is much more complicated than in beginning)
The largest problem is as you said that there is no group conversion possible. They have private [tool](https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/vector-drawable-tool/src/main/java/com/android/ide/common/vectordrawable) but maybe in future they will share It to public sdk (not sure why not already). I hope they will implement this feature soon.

**Comment by rayliverified** [comment]
Thanks for making this tool and your explanation!

**Comment by rayliverified** [comment]
Hello everyone! I just found a tool that appears to be updated and supports batch conversion too. It has all the features of this tool and more. 

https://github.com/a-student/SvgToVectorDrawableConverter.Web

Not to throw any shade at this repo. This tool has helped me so much over the years I'm hesitant to use anything new just out of habit!
