### ISSUE TITLE
Can't convert this svg correctly.

### ISSUE THREAD

**Issue by nmDejamobile** [inloop/svg2android#82]
It's exported from Adobe Illustrator and I tried any export settings (export, save as copy) every time the striking bar is horizontal instead of having a 45° angle.
Attached are [the svg file and the generated xml](https://github.com/inloop/svg2android/files/1085409/Archive.zip).

**Comment by conrad-heimbold** [comment]
**RTMF!** 
Quote from the README.md of this project: 
> **Not supported**: text element (export manually to path), gradients and patterns, **_matrix transforms_** 

Your ic_watch_disabled.svg file however contains a matrix-transform element in line 6 (open the file in a text editor to see): 
> \<rect x="-2.2" y="21.1" **transform="matrix(0.7071 -0.7071 0.7071 0.7071 -9.9443 23.9993)"** width="52.4" height="5.9"/\>

**Get rid of this transform attribute!** Otherwise, converting will definitely **not** work! 
> #### How to remove transforms in Inkscape
> - Open svg file in Inkscape
> - Go to Edit -> XML Editor (or press CTRL SHIFT X )
> - Find "transform"  attributes in layers or objects and delete them
> #### How to move all objects altogether without creating another transform attributes
> - Go to Edit -> Select All in All Layers (or press CTRL A)
> - Go to Object -> Transform
>  In Transform panel
> - **Uncheck Relative move and check Apply to each object separately**
> - Set Horizontal and Vertical values according to your needs and
> - click Apply

Other way to do it: 
* convert the striking bar to a path in Inkscape (CTRL+ALT+C)
* move the edges by hand (do **not** use the transform / rotate functionality!)

Your way how to do it might be different.
I think you can figure out how to get Inkscape by yourself...

**Comment by conrad-heimbold** [comment]
**/close**
